# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/virendra.shakya/Zircon/microservice.petsitter.reg/zcPetSitterRegistration/zcShared/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/virendra.shakya/Zircon/microservice.petsitter.reg/zcPetSitterRegistration/zcShared/exec/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/virendra.shakya/Zircon/microservice.petsitter.reg/zcPetSitterRegistration/zcShared/exec/sample/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/virendra.shakya/Zircon/microservice.petsitter.reg/zcPetSitterRegistration/zcShared/exec/test/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/virendra.shakya/Zircon/microservice.petsitter.reg/zcPetSitterRegistration/zcShared/exec/test/lib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/virendra.shakya/Zircon/microservice.petsitter.reg/zcPetSitterRegistration/zcShared/lib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/Catch2/Catch2Config.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/Catch2/Catch2ConfigVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/Catch2/Catch2Targets.cmake))

/Users/virendra.shakya/Zircon/microservice.petsitter.reg/XCODE-BUILD/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/virendra.shakya/Zircon/microservice.petsitter.reg/zcPetSitterRegistration -B/Users/virendra.shakya/Zircon/microservice.petsitter.reg/XCODE-BUILD
