# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

cache:
    paths:
    - build/

build:
  stage: build

  # install the necessary build tools when needed
  before_script:
      # Install build dependencies
      - apt-get update && apt-get -y install cmake

  script:
        - mkdir build
        - cd build
        - cmake ..
        - make
